New fix window.opener unaccess property "document" or = null
I think this error appear when user never click to open popup preference
wizard 'users/pref_wizard/index.php' OR with fresh browser session.
window.opener.document (location are about:blank in ff)
& unautorized 4 change (not same domain)

(firefox)
TypeError: window.opener is null
(chromium)
Uncaught TypeError: Cannot read property 'document' of null
ATutor.js:582