fix toggle no work due an window.opener.document access denied
Prevent for continue to interpret javascript if stopping with
Error: Permission denied to access property "document"
Maybe rule browser "Same-origin policy" or unexisting object.

On course sidebar, toggle unwork & print "toggle" in place of +
for simply see this (js) error, go to login.php ;-)

this function is called in jscript/ATutor_js.php on line 381
ATutor.users.preferences.setStyles()