Fix: social settings after saved preferences
when member save prefs and resave prefs, occur an error.
The unserialized prefs ares in wrong format because of \" inside.
Probably wooops

Fatal error: Call to a member function setProfile() on a non-object in
ATutor/mods/_standard/social/settings.php on line 67